version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "composer install --no-interaction &&
             npm install &&
             php artisan migrate --force &&
             php artisan db:seed --force &&
             php-fpm"

  nginx:
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
