version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-auction-app-prod
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - loan-auction-network
    depends_on:
      - mysql
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  nginx:
    image: nginx:alpine
    container_name: loan-auction-nginx-prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - loan-auction-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: loan-auction-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - loan-auction-network

  # redis:
  #   image: redis:alpine
  #   container_name: loan-auction-redis-prod
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data_prod:/data
  #   networks:
  #     - loan-auction-network

networks:
  loan-auction-network:
    driver: bridge

volumes:
  mysql_data_prod:
    driver: local
  # redis_data_prod:
  #   driver: local
